# Generated by Django 3.2.9 on 2022-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='school number'),
        ),
    ]
