# Generated by Django 3.2.9 on 2022-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0002_school_school_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about_school',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='About'),
        ),
    ]
