# Generated by Django 3.2.9 on 2022-04-13 01:37

from django.db import migrations, models
import students_school.models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0003_school_about_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.CharField(blank=True, default=students_school.models.generate_number, editable=False, max_length=10, null=True, unique=True, verbose_name='school number'),
        ),
    ]
