# Generated by Django 3.2.9 on 2022-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0005_remove_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='null', max_length=10, verbose_name='gender'),
        ),
    ]
