# Generated by Django 3.2.9 on 2022-04-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default='060b1388-8754-4c90-a191-73f87ddf65ba', on_delete=django.db.models.deletion.CASCADE, to='students_school.school', verbose_name='school'),
            preserve_default=False,
        ),
    ]
