# Generated by Django 3.2.9 on 2022-04-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_librarian_library'),
        ('students_school', '0007_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='library',
            field=models.ForeignKey(default='fddd308235564732a77b8767904d52fb', on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
            preserve_default=False,
        ),
    ]
