# Generated by Django 3.2.9 on 2022-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0009_alter_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
