# Generated by Django 3.2.9 on 2022-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_school', '0011_school_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(choices=[('Choose', 'Choose'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3'), ('PRIMARY 6', 'PRIMARY 6'), ('PRIMARY 5', 'PRIMARY 5'), ('PRIMARY 4', 'PRIMARY 4'), ('PRIMARY 3', 'PRIMARY 3'), ('PRIMARY 2', 'PRIMARY 2'), ('PRIMARY 1', 'PRIMARY 1')], max_length=60, verbose_name='Class'),
        ),
    ]
