# Generated by Django 3.2.9 on 2022-04-08 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('about', models.TextField(max_length=1000, verbose_name='About Book')),
                ('stock', models.IntegerField(verbose_name='book quantity')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.library')),
            ],
        ),
    ]
