# Generated by Django 3.2.9 on 2022-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
