# Generated by Django 3.2.9 on 2022-07-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='datetime',
        ),
    ]
