# Generated by Django 3.2.9 on 2022-08-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_librarian_library'),
        ('books', '0005_newbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbooks',
            name='library',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
            preserve_default=False,
        ),
    ]
