# Generated by Django 3.2.9 on 2022-07-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
