# Generated by Django 3.2.9 on 2022-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_schoolrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrequests',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
