# Generated by Django 4.0.6 on 2022-07-19 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_librarian_library'),
        ('request', '0003_alter_schoolrequests_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrequests',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
        ),
        migrations.AddField(
            model_name='studentrequests',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
        ),
    ]
