# Generated by Django 3.2.9 on 2022-04-08 23:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='library id')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='library name')),
                ('location', models.CharField(max_length=255, unique=True, verbose_name='library location')),
                ('about', ckeditor.fields.RichTextField()),
                ('gps_location', models.CharField(max_length=100, verbose_name='Ghana GPS')),
            ],
            options={
                'verbose_name': 'library',
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='librarian id')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.library')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
